version: 2.0.{build}

branches:
  only:
    - Master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Debug

#before_build:
#  - nuget restore
  
build:
  project: dashboardig.sln

after_build:
  - ps: .\nuget\pack.ps1

test: off

artifacts:
  - path: Codeplex.Dashboarding.Wpf\bin\Debug\DotNetProjects.Dashboarding.dll
    name: DotNetProjects.Dashboarding.dll
  - path: Codeplex.Dashboarding.Wpf\bin\Debug\DotNetProjects.Dashboarding.pdb
    name: DotNetProjects.Dashboarding.pdb
  - path: '**\DotNetProjects.*.nupkg'

#uncomment to publish to NuGet
deploy:
  provider: NuGet
  api_key:
    secure: bdhemLvYgto+o1hjkJ9OhVRANxW6+U9RTGQre/KqyV3mFWmN5BQA6ZpMoHbjsaJW
  artifact: /.*\.nupkg/
  
  
  